name: many_models
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - pip=24.0
  - pip:
    - azureml-mlflow==1.55.0
    - mltable==1.6.1
    - azureml-dataset-runtime==1.55.0
    - azureml-telemetry==1.55.0
    - pandas==1.5.3
    - numpy==1.23.5
    - scikit-learn==1.4.1post1
    - pillow==10.2.0
    - azure-ai-ml==1.13.0
    - azure-identity==1.15.0
    - ipykernel==6.24.0
    - python-dotenv==1.0.1
    - azureml-fsspec==1.3.1