$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: Many Model Training
description: parallel job to train many models with partition_keys on mltable input
experiment_name: many-model-parallel-job

settings:
  default_compute: azureml:dev-cluster

jobs:
  partition_job:
    type: command
    component: ../src/components/partition_data/partition_data.yaml

    inputs:
      data_source:
        type: uri_file
        path: ../data/oj_sim_sales/train_subset.csv
      partition_keys: Store,Brand
    outputs:
      tabular_output_data:
        type: mltable
        mode: rw_mount

  distributed_training:
    type: parallel
    compute: azureml:dev-cluster
    
    inputs:
      data_source: 
        path: ${{parent.jobs.partition_job.outputs.tabular_output_data}}
        type: mltable
        mode: direct
      drop_cols: "Advert,Store,Brand"
      target_col: "Revenue"
      date_col: "WeekStarting"
      tracking_uri: "<YOUR_WORKSPACE_TRACKING_URI>"
    
    outputs:
      model_folder:
        type: uri_folder
        mode: rw_mount

    partition_keys:
      - Store
      - Brand
    resources:
      instance_count: 10

    error_threshold: -1
    mini_batch_error_threshold: 5
    logging_level: "INFO"
    input_data: ${{inputs.data_source}}
    max_concurrency_per_instance: 2
    retry_settings:
      max_retries: 2
      timeout: 600

    task:
      type: run_function
      code: ../src/
      entry_script: parallel_train.py
      environment:
        image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240226.v1
        conda_file: ../environment/conda.yaml
      program_arguments: >-
        --drop_cols ${{inputs.drop_cols}}
        --target_col ${{inputs.target_col}}
        --date_col ${{inputs.date_col}}
        --model_folder ${{outputs.model_folder}}
        --tracking_uri ${{inputs.tracking_uri}}